# Generated by Django 4.2.8 on 2024-01-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
